version: '3'
services:
  spring-app:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/notes_db
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SERVER_PORT=8081
    ports:
      - "8081:8081"
    volumes:
      - ./uploads:/home/project/uploads
    depends_on:
      - mysql
    

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: notes_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  uploads: 
  mysql: 
